---
dependencies:
  - role: de.iteratec.hh.common
  - role: de.iteratec.hh.vagrant
  - role: de.iteratec.hh.docker-mirror
    dmirror_home: "{{ DMIRROR_HOME }}"
    dmirror_domain: "{{ acia_vagrant_hostnet_netpart }}.1"
    dmirror_ip: "{{ acia_vagrant_hostnet_netpart }}.1"
    dmirror_port: "{{ acia_dmirror_port }}"
    dmirror_pki_password: "{{ PKI_PASSWORD }}"
    dmirror_pki_countrycode: "{{ aci_docker_pki_countrycode }}"
    dmirror_pki_state: "{{ aci_docker_pki_state }}"
    dmirror_pki_locality: "{{ aci_docker_pki_locality }}"
    dmirror_pki_organization: "{{ aci_docker_pki_organization }}"
